{{- $resourcename := include "docs-csc.origBuilderName" . -}}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ $resourcename }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
{{ $resourcename | list $ | include "docs-csc.componentLabels" | indent 4 }}
spec:
  triggers:
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: {{ $resourcename | list $ | include "docs-csc.latestImageName" | squote }}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile.builder
      buildArgs:
{{ list .Values "builder" | include "docs-csc.imageBuildArg" | indent 8 }}
  source:
{{ include "docs-csc.gitSource" . | indent 4 }}