{{- $resourcename := include "docs-csc.altName" . -}}
{{- $servername := include "docs-csc.altServerName" . -}}
{{- $imagename := $resourcename | list $ | include "docs-csc.latestImageName" -}}
{{- $componentlabels := $resourcename | list $ | include "docs-csc.componentLabels" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $resourcename }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
{{ $componentlabels | indent 4 }}
  annotations:
    image.openshift.io/triggers: |-
{{ list $imagename $servername | include "docs-csc.deploymentTrigger" | indent 6 }}
spec:
  selector:
    matchLabels:
{{ include "docs-csc.selectorLabels" . | indent 6 }}
{{ $componentlabels | indent 6 }}
  replicas: {{ .Values.components.alternate.replicaCount | default 1 }}
  template:
    metadata:
      labels:
{{ include "docs-csc.labels" . | indent 8 }}
{{ $componentlabels | indent 8 }}
    spec:
      volumes:
{{ include "translation.buildsVolume" . | indent 8 }}
        - name: nginx-location
          configMap:
            name: {{ include "docs-csc.altConfigName" . }}
            defaultMode: 420
      containers:
        - name: {{ $servername }}
          image: {{ $imagename | squote }}
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: nginx-location
              mountPath: /opt/app-root/etc/nginx.default.d
            - name: {{ include "translation.buildsVolumeName" . }}
              mountPath: /opt/app-root/src
              subpath: /builds
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%