{{- range $lang := .Values.translator.languages }}
---
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ $lang.code | printf "%s-%s-%s-%s" ($ | include "docs-csc.name") "init" "translation" }}
  labels:
{{ $ | include "docs-csc.labels" | indent 4 }}
  annotations:
{{ $ | include "docs-csc.annotations" | indent 4 }}
spec:
  template:
{{ . | list $ | include "translation.jobSpec" | indent 4 }}
{{- end -}}
