kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "docs-csc.altVolumeClaimName" . }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
{{ include "docs-csc.altName" . | list $ | include "docs-csc.componentLabels" | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.components.translator.storageCapacity | default "2Gi" }}