{{- $resourcename := include "docs-csc.altVolumeClaimName" . -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $resourcename }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
{{ $resourcename | list $ | include "docs-csc.componentLabels" | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.components.translator.storageCapacity | default "2Gi" }}