{{- if not (include "networking.siteHost" . | hasSuffix ".rahtiapp.fi") -}}
{{- if .Values.site.acme.useResourceLookup | default false -}}
{{- dict "name" (include "networking.acmeAccountKeySecretName" .)
         "kind" "Secret"
         "apiVersion" "v1"
         "namespace" .Release.Namespace
    | include "docs-csc.resourceLookup" }}
{{- else -}}
{{- include "networking.newAcmeAccountKeySecret" . }}
{{- end -}}
{{- end -}}