{{- if .Values.components.translator.useResourceLookup | default false }}
{{ dict "name" (include "translation.translatorSecretName" .)
         "kind" "Secret"
         "apiVersion" "v1"
         "namespace" .Release.Namespace
    | include "docs-csc.resourceLookup" }}
{{- else }}
{{ include "translation.newTranslatorSecret" . }}
{{- end }}