{{- $secretname := include "docs-csc.origWebHookSecretName" . -}}
{{/* Attempt to lookup existing secret, generate a new one on fail. */}}
{{- $secretkey := $secretname
                  | lookup "v1" "Secret" .Release.Namespace
                  | dig "data" "WebHookSecretKey" (randAlphaNum 32 | b64enc) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secretname }}
  labels:
{{ include "docs-csc.labels" .| indent 4 }}
  annotations:
{{ include "docs-csc.annotations" . | indent 4 }}
data:
  WebHookSecretKey: {{ $secretkey }}
type: Opaque