{{- if not (include "networking.siteHost" . | hasSuffix ".rahtiapp.fi") }}
{{- if .Values.site.acme.useResourceLookup | default false }}
{{ lookup "v1"
          "Secret"
          .Release.Namespace
          (include "networking.acmeEabSecretName" .)
   | dig "data" dict
   | list $
   | include "networking.acmeEabSecret" }}
{{- else }}
{{ include "networking.newAcmeEabSecret" . }}
{{- end }}
{{- end }}