{{- $secretname := include "networking.webHookSecretName" . -}}
{{/* Attempt to lookup existing key, generate a new one on fail. */}}
{{- $existingsecret := lookup "v1" "Secret" .Release.Namespace $secretname | default nil -}}
{{- if $existingsecret }}
{{ $existingsecret | toYaml }}
{{- else }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secretname }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
{{ include "docs-csc.origName" . | list $ | include "docs-csc.componentLabels" | indent 4 }}
data:
  WebHookSecretKey: {{ randAlphaNum 24 | b64enc }}
type: Opaque
{{- end }}