{{- if not (include "networking.siteHost" . | hasSuffix ".rahtiapp.fi") }}
{{- if .Values.site.acme.useResourceLookup | default false }}
{{- dict "name" (include "networking.acmeEabSecretName" .)
         "kind" "Secret"
         "apiVersion" "v1"
         "namespace" .Release.Namespace
    | include "docs-csc.resourceLookup" }}
{{- else }}
{{- include "networking.newAcmeEabSecret" . }}
{{- end }}
{{- end }}