{{- $secretname := include "docs-csc.translatorSecretName" . -}}
{{/* Attempt to lookup existing secret. */}}
{{- $existing := lookup "v1" "Secret" $.Release.Namespace $secretname -}}
{{- $existingdata := dig "data" $existing (dict) -}}
{{- $translatorvalues := .Values.translator -}}
{{- $valuesdata := dict "openAiApiKey" (dig "openAi" "apiKey" "" $translatorvalues)
                        "resticPassword" (dig "restic" "password" "" $translatorvalues)
                        "osApplicationCredentialId" (dig "os" "applicationCredentialId" "" $translatorvalues)
                        "osApplicationCredentialSecret" (dig "os" "applicationCredentialSecret" "" $translatorvalues) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secretname }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
type: Opaque
data:
{{- range $key, $value := $valuesdata }}
{{- $existingvalue := $key | get $existingdata -}}
{{- $secretvalue := $value | default $existingvalue
                           | required ($key | printf "%s is required!") }}
{{ $secretvalue | printf "%s: %s" $key | indent 2 -}}
{{ end -}}