{{- $secretname := include "docs-csc.translatorSecretName" . -}}
{{/* Attempt to lookup existing secret. */}}
{{- $existingdata := $secretname | lookup "v1" "Secret" $.Release.Namespace
                                 | dig "data" dict -}}
{{- $datafilename := .Values.translator.secretsFile | default "" -}}
{{- $filedata := (empty $datafilename | not)
                | ternary ($.Files.Get $datafilename | fromYaml | default dict)
                          dict
                | default dict -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $secretname }}
  labels:
{{ include "docs-csc.labels" . | indent 4 }}
  annotations:
{{ include "docs-csc.annotations" . | indent 6 }}
type: Opaque
data: {{ range $secret := list "openAiApiKey"
                               "resticPassword"
                               "osApplicationCredentialId"
                               "osApplicationCredentialSecret" }}
  {{ $secret | printf "%s: " }}{{ $secret | get $filedata
                                  | b64enc
                                  | default ($secret | get $existingdata)
                                  | required ($secretname | printf "%s is required for %s!" $secret)}}
{{- end -}}