ARG builder_image
FROM ${builder_image}

LABEL maintainer="CSC Service Desk <servicedesk@csc.fi>"

ARG restic_image
COPY --from=${restic_image} \
     /usr/bin/restic \
     /usr/bin/restic

ADD translation/requirements.txt ./

RUN \
  pip install --upgrade pip \
&& \
  pip3 install \
         --use-pep517 \
         --no-cache-dir \
         --no-deps \
         --requirement=requirements.txt

ADD translation/translator/ ./translator/
ADD translation/refresh_translation.py \
    translation/clear_cache.py \
    ./

ADD --chown=0:0 \
    --chmod=774 \
  scripts/sparse-clone.bash /sparse-clone.bash

ADD --chown=0:0 \
    --chmod=774 \
  translation/entrypoint.translator.bash /entrypoint.bash

ARG repo_host=github.com
ARG repo_org=CSCfi
ARG repo_name=csc-user-guide
ARG repo_branch=master
ENV REPO_HOST=${repo_host} \
    REPO_ORG=${repo_org} \
    REPO_NAME=${repo_name} \
    REPO_BRANCH=${repo_branch} \
    DOCS_DIR=docs

ENTRYPOINT ["/entrypoint.bash"]
