git:
  uri: https://github.com/CSCfi/csc-user-guide.git
  ref: master

# Defaults to 'preview' if not set:
environment: production

nameOverride: null

base:
  image: ubi9
  tag: 9.8-1786985871

server:
  image: ubi9/nginx-126
  tag: 9.8-1787043707

localRegistry: image-registry.openshift-image-registry.svc:5000

site:
  # The server hostname. Alternate languages will be available
  # under subpaths /<lang code>:
  host: docs.csc.fi

  matomoUrl: https://mwa.2.rahtiapp.fi/

  # List of IP addresses/ranges to allow access from. Format is
  #   ipAllowlist:
  #     - 127.0.0.1
  #     - 192.167.0.0/16
  #
  # Allow any if filename not defined or ipAllowlist is empty:
  ipAllowlistFile: iplist.yaml

  acme:
    useResourceLookup: false
    issuerName: null

    # ACME certificate details. Format is
    #   email: recipient@example.org
    #   server: https://acme.api.example.org
    #   certificateDuration: 2160h
    #   certificateRenewBefore: 720h
    #   eabKeyID: <ACME account EAB key ID>
    #   eabHmacKey: <ACME account EAB HMAC key>
    #   accountKey: |
    #     -----BEGIN RSA PRIVATE KEY-----
    #     <ACME account private key>
    #     -----END RSA PRIVATE KEY-----
    #
    # Has no effect if site.host is not set or ends in '.rahtiapp.fi':
    acmeFile: acme.yaml

components:
  original:
    # GitHub repo for the English site.
    # (defaults are defined in /Containerfile):
    #
    # repo:
    #   host: github.com
    #   org: CSCfi
    #   name: csc-user-guide
    #   branch: master

    configBranchOverride: null

    # Matomo site ID for the English site:
    matomoSiteId: 1

    # Number of replicas for English site deployment,
    # Defaults to 1 if not set:
    replicaCount: 3

  translator:
    # GitHub repo where Markdown files are fetched for translation.
    # (defaults are defined in /translation/Containerfile.translator):
    #
    # repo:
    #   host: github.com
    #   org: CSCfi
    #   name: csc-user-guide
    #   branch: master

    configBranchOverride: null

    useResourceLookup: false

    # Translator secrets. An attempt is made to lookup existing values.
    # Values defined in secretsFile take precedence over lookup. Format is
    #   openAiApiKey: <string> (not needed if translator.restoreOnly is set)
    #   resticPassword: <string>
    #   osApplicationCredentialId: <string>
    #   osApplicationCredentialSecret: <string>
    # Keys are case-sensitive:
    secretsFile: translator.yaml

    languages:
      - code: fi
        name: Finnish
        matomoSiteId: 24
      # - code: se
      #   name: Swedish
      #   matomoSiteId: ??

    # Allows for a deployment where pages are not translated,
    # but only restored from the latest restic snapshot.
    # Defaults to false:
    restoreOnly: false

    # The translation schedule as cron expression.
    # Defaults to '0 0 * * 1-5', i.e. weekday midnights:
    schedule: 0 0 * * 1-5

    osAuthUrl: https://pouta.csc.fi:5001/v3
    restic:
      image: ghcr.io/restic/restic
      tag: 0.19.1
      repository: swift:docs-restic:/translations

      # This is not the server hostname. Only used as the hostname in restic snapshots:
      host: docs.csc.fi

    # This probably shouldn't be touched. Determines the path where
    # the translated files are cached before they're saved into
    # a restic snapshot. Used for continuing an errored translation
    # without having to start over:
    cache:
      container: docs-restic
      prefix: cache

    # Defaults to 2Gi if not set:
    storageCapacity: null

  alternate:
    # repo:
    #   host: github.com
    #   org: CSCfi
    #   name: csc-user-guide
    #   branch: master

    configBranchOverride: null

    replicaCount: 1
